name: Git tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  check_comment_edit:
    runs-on: self-hosted
    timeout-minutes: 1
    container: kel.osll.ru:8083/docker/ubuntu:git-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run check_comment_edit.sh
      run: |
         cp -r /__e/02-git-tests ./
         cd 02-git-tests
         ./check_comment_edit.sh
      shell: bash
  check_branch:    
    runs-on: self-hosted
    timeout-minutes: 1
    container: kel.osll.ru:8083/docker/ubuntu:git-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run check_branch.sh
      run: |
         cp -r /__e/02-git-tests ./
         cd 02-git-tests
         ./check_branch.sh
      shell: bash
  check_amend:    
    runs-on: self-hosted
    timeout-minutes: 1
    container: kel.osll.ru:8083/docker/ubuntu:git-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run check_amend.sh
      run: |
         cp -r /__e/02-git-tests ./
         cd 02-git-tests
         ./check_amend.sh
      shell: bash
  check_squash:
    runs-on: self-hosted
    timeout-minutes: 1
    container: kel.osll.ru:8083/docker/ubuntu:git-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run check_squash.sh
      run: |
         cp -r /__e/02-git-tests ./
         cd 02-git-tests
         ./check_squash.sh
      shell: bash
  check_cherry_pick:    
    runs-on: self-hosted
    timeout-minutes: 1
    container: kel.osll.ru:8083/docker/ubuntu:git-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run check_cherry_pick.sh
      run: |
         cp -r /__e/02-git-tests ./
         cd 02-git-tests
         ./check_cerry_pick.sh
      shell: bash
  check_revert:    
    runs-on: self-hosted
    timeout-minutes: 1
    container: kel.osll.ru:8083/docker/ubuntu:git-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run check_revert.sh
      run: |
         cp -r /__e/02-git-tests ./
         cd 02-git-tests
         ./check_revert.sh
      shell: bash
  check_merge:    
    runs-on: self-hosted
    timeout-minutes: 1
    container: kel.osll.ru:8083/docker/ubuntu:git-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run check_merge.sh
      run: |
         cp -r /__e/02-git-tests ./
         cd 02-git-tests
         ./check_merge.sh
      shell: bash
